<html>
<head>
<title>Détail de la correction.</title>
<style>
p.titre {font-weight: bold; font-family: Arial; font-size: 14pt;}
span.titreTest {font-weight: bold; font-family: Arial; font-size: 12pt; text-decoration: underline;}
span.verdictTest {font-family: Arial; font-size: 12pt;}
span.titreException {font-family: Arial; font-size: 12pt; text-decoration: underline;}
span.titreMessage {font-family: Arial; font-size: 12pt; text-decoration: underline;}
span.titrePileAppel {font-family: Arial; font-size: 12pt; text-decoration: underline;}
span.titreDiagnostic {font-family: Arial; font-size: 12pt; font-style: italic; color: #3300CC;}
span.pileAppel {font-family: Arial; font-size: 11pt;}
</style>
</head>
<body>
<p class="titre">Voici les tests qui ont posé des problèmes à votre exécutable. Cette liste est vide si tous se sont déroulés sans incident.</p>
<p><span class="titreTest">testCreateCategory(b):</span> <span class="verdictTest">Votre exécutable a échoué en levant une exception.</span></p>
<p><span class="titreException">Exception levée:</span> java.lang.NullPointerException</p>
<p><span class="titrePileAppel">Pile d'appel:</span> <br><span class="pileAppel">java.lang.NullPointerException<br>	at b.a(Unknown Source)<br>	at b.testCreateCategory(Unknown Source)<br>	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br>	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)<br>	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br>	at java.lang.reflect.Method.invoke(Method.java:498)<br>	at junit.framework.TestCase.runTest(TestCase.java:176)<br>	at junit.framework.TestCase.runBare(TestCase.java:141)<br>	at junit.framework.TestResult$1.protect(TestResult.java:122)<br>	at junit.framework.TestResult.runProtected(TestResult.java:142)<br>	at junit.framework.TestResult.run(TestResult.java:125)<br>	at junit.framework.TestCase.run(TestCase.java:129)<br>	at junit.framework.TestSuite.runTest(TestSuite.java:252)<br>	at junit.framework.TestSuite.run(TestSuite.java:247)<br>	at junit.framework.TestSuite.runTest(TestSuite.java:252)<br>	at junit.framework.TestSuite.run(TestSuite.java:247)<br>	at u.tester(Unknown Source)<br>	at u.testerEtQuitter(Unknown Source)<br>	at Tests.main(Unknown Source)<br></span></p>
<p><span class="titreDiagnostic">testCreateCategory(b): null</span></p>
<br>
<p><span class="titreTest">testCreateProduct(f):</span> <span class="verdictTest">Votre exécutable a échoué en levant une exception.</span></p>
<p><span class="titreException">Exception levée:</span> java.lang.NullPointerException</p>
<p><span class="titrePileAppel">Pile d'appel:</span> <br><span class="pileAppel">java.lang.NullPointerException<br>	at f.a(Unknown Source)<br>	at f.testCreateProduct(Unknown Source)<br>	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br>	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)<br>	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br>	at java.lang.reflect.Method.invoke(Method.java:498)<br>	at junit.framework.TestCase.runTest(TestCase.java:176)<br>	at junit.framework.TestCase.runBare(TestCase.java:141)<br>	at junit.framework.TestResult$1.protect(TestResult.java:122)<br>	at junit.framework.TestResult.runProtected(TestResult.java:142)<br>	at junit.framework.TestResult.run(TestResult.java:125)<br>	at junit.framework.TestCase.run(TestCase.java:129)<br>	at junit.framework.TestSuite.runTest(TestSuite.java:252)<br>	at junit.framework.TestSuite.run(TestSuite.java:247)<br>	at junit.framework.TestSuite.runTest(TestSuite.java:252)<br>	at junit.framework.TestSuite.run(TestSuite.java:247)<br>	at u.tester(Unknown Source)<br>	at u.testerEtQuitter(Unknown Source)<br>	at Tests.main(Unknown Source)<br></span></p>
<p><span class="titreDiagnostic">testCreateProduct(f): null</span></p>
<br>
<p><span class="titreTest">testUpdateProduct(f):</span> <span class="verdictTest">Votre exécutable a échoué en levant une exception.</span></p>
<p><span class="titreException">Exception levée:</span> java.lang.NullPointerException</p>
<p><span class="titrePileAppel">Pile d'appel:</span> <br><span class="pileAppel">java.lang.NullPointerException<br>	at f.a(Unknown Source)<br>	at f.testUpdateProduct(Unknown Source)<br>	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br>	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)<br>	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br>	at java.lang.reflect.Method.invoke(Method.java:498)<br>	at junit.framework.TestCase.runTest(TestCase.java:176)<br>	at junit.framework.TestCase.runBare(TestCase.java:141)<br>	at junit.framework.TestResult$1.protect(TestResult.java:122)<br>	at junit.framework.TestResult.runProtected(TestResult.java:142)<br>	at junit.framework.TestResult.run(TestResult.java:125)<br>	at junit.framework.TestCase.run(TestCase.java:129)<br>	at junit.framework.TestSuite.runTest(TestSuite.java:252)<br>	at junit.framework.TestSuite.run(TestSuite.java:247)<br>	at junit.framework.TestSuite.runTest(TestSuite.java:252)<br>	at junit.framework.TestSuite.run(TestSuite.java:247)<br>	at u.tester(Unknown Source)<br>	at u.testerEtQuitter(Unknown Source)<br>	at Tests.main(Unknown Source)<br></span></p>
<p><span class="titreDiagnostic">testUpdateProduct(f): null</span></p>
<br>
<p><span class="titreTest">testUpdateItem(e):</span> <span class="verdictTest">Votre exécutable a échoué en levant une exception.</span></p>
<p><span class="titreException">Exception levée:</span> java.lang.NullPointerException</p>
<p><span class="titrePileAppel">Pile d'appel:</span> <br><span class="pileAppel">java.lang.NullPointerException<br>	at e.a(Unknown Source)<br>	at e.testUpdateItem(Unknown Source)<br>	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br>	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)<br>	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br>	at java.lang.reflect.Method.invoke(Method.java:498)<br>	at junit.framework.TestCase.runTest(TestCase.java:176)<br>	at junit.framework.TestCase.runBare(TestCase.java:141)<br>	at junit.framework.TestResult$1.protect(TestResult.java:122)<br>	at junit.framework.TestResult.runProtected(TestResult.java:142)<br>	at junit.framework.TestResult.run(TestResult.java:125)<br>	at junit.framework.TestCase.run(TestCase.java:129)<br>	at junit.framework.TestSuite.runTest(TestSuite.java:252)<br>	at junit.framework.TestSuite.run(TestSuite.java:247)<br>	at junit.framework.TestSuite.runTest(TestSuite.java:252)<br>	at junit.framework.TestSuite.run(TestSuite.java:247)<br>	at u.tester(Unknown Source)<br>	at u.testerEtQuitter(Unknown Source)<br>	at Tests.main(Unknown Source)<br></span></p>
<p><span class="titreDiagnostic">testUpdateItem(e): null</span></p>
<br>
<p><span class="titreTest">testUpdateCategory(b):</span> <span class="verdictTest">Votre exécutable a échoué en levant une exception.</span></p>
<p><span class="titreException">Exception levée:</span> java.lang.NullPointerException</p>
<p><span class="titrePileAppel">Pile d'appel:</span> <br><span class="pileAppel">java.lang.NullPointerException<br>	at b.a(Unknown Source)<br>	at b.testUpdateCategory(Unknown Source)<br>	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br>	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)<br>	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br>	at java.lang.reflect.Method.invoke(Method.java:498)<br>	at junit.framework.TestCase.runTest(TestCase.java:176)<br>	at junit.framework.TestCase.runBare(TestCase.java:141)<br>	at junit.framework.TestResult$1.protect(TestResult.java:122)<br>	at junit.framework.TestResult.runProtected(TestResult.java:142)<br>	at junit.framework.TestResult.run(TestResult.java:125)<br>	at junit.framework.TestCase.run(TestCase.java:129)<br>	at junit.framework.TestSuite.runTest(TestSuite.java:252)<br>	at junit.framework.TestSuite.run(TestSuite.java:247)<br>	at junit.framework.TestSuite.runTest(TestSuite.java:252)<br>	at junit.framework.TestSuite.run(TestSuite.java:247)<br>	at u.tester(Unknown Source)<br>	at u.testerEtQuitter(Unknown Source)<br>	at Tests.main(Unknown Source)<br></span></p>
<p><span class="titreDiagnostic">testUpdateCategory(b): null</span></p>
<br>
<p><span class="titreTest">testCreateItem(e):</span> <span class="verdictTest">Votre exécutable a échoué en levant une exception.</span></p>
<p><span class="titreException">Exception levée:</span> java.lang.NullPointerException</p>
<p><span class="titrePileAppel">Pile d'appel:</span> <br><span class="pileAppel">java.lang.NullPointerException<br>	at e.a(Unknown Source)<br>	at e.testCreateItem(Unknown Source)<br>	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br>	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)<br>	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br>	at java.lang.reflect.Method.invoke(Method.java:498)<br>	at junit.framework.TestCase.runTest(TestCase.java:176)<br>	at junit.framework.TestCase.runBare(TestCase.java:141)<br>	at junit.framework.TestResult$1.protect(TestResult.java:122)<br>	at junit.framework.TestResult.runProtected(TestResult.java:142)<br>	at junit.framework.TestResult.run(TestResult.java:125)<br>	at junit.framework.TestCase.run(TestCase.java:129)<br>	at junit.framework.TestSuite.runTest(TestSuite.java:252)<br>	at junit.framework.TestSuite.run(TestSuite.java:247)<br>	at junit.framework.TestSuite.runTest(TestSuite.java:252)<br>	at junit.framework.TestSuite.run(TestSuite.java:247)<br>	at u.tester(Unknown Source)<br>	at u.testerEtQuitter(Unknown Source)<br>	at Tests.main(Unknown Source)<br></span></p>
<p><span class="titreDiagnostic">testCreateItem(e): null</span></p>
<br>
</body>
</html>
